### ISSUE TITLE
Unittests failing on import

### ISSUE THREAD

**Issue by RobertBeilich** [SAP/ui5-webcomponents-react#113]
**Describe the bug**
When adding e.g. the `<Select>` with `<Option>` jest tests fail with

```

    /Users/<redacted>/test-app/node_modules/@ui5/webcomponents/dist/Popover.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import litRender from "@ui5/webcomponents-base/src/renderer/LitRenderer.js";
                                                                                                    ^^^^^^^^^

    SyntaxError: Unexpected identifier

      at ScriptTransformer._transformAndBuildScript (node_modules/@jest/transform/build/ScriptTransformer.js:471:17)
      at ScriptTransformer.transform (node_modules/@jest/transform/build/ScriptTransformer.js:513:25)
      at Object.<anonymous> (node_modules/@ui5/webcomponents-react/cjs/main.development.js:7:18)

  console.info node_modules/@ui5/webcomponents-react-base/cjs/base.development.js:1934
    2019-09-10 11:07:33 Device API logging initialized -

  console.info node_modules/@ui5/webcomponents-react-base/cjs/base.development.js:1934
    2019-09-10 11:07:33 OS detection returned no result - DEVICE
```

**To Reproduce**
- yarn create react-app test-app --typescript
- yarn add @ui5/webcomponents-react
- yarn test (test passes)
- add to App.tsx:
```
        <Select disabled={false}>
          <Option selected icon="sap-icon://add">
            Test 1
          </Option>
          <Option icon="sap-icon://add">
            Test 2
          </Option>
          <Option icon="sap-icon://add">
            Test 3
          </Option>
          <Option icon="sap-icon://add">
            Test 4
          </Option>
          <Option icon="sap-icon://add">
            Test 5
          </Option>
        </Select>
```
- yarn start (verifying that the app works as expected)
- yarn test (test fails on import)

**Expected behavior**
Test passing

**Desktop (please complete the following information):**
 - OS: MacOS

**Comment by vbersch** [comment]
Hi,

This is a general issue of jest/jsdom with Web Components/Custom Elements.
-> https://github.com/jsdom/jsdom/issues/1030

See https://github.com/SAP/ui5-webcomponents-react/blob/master/config/jest.config.js
for a working jest config file for testing Web Components.
