### ISSUE TITLE
Table: TableRow memoization not working when mode is MultiSelect

### ISSUE THREAD

**Issue by gurkirpalgill** [SAP/ui5-webcomponents-react#3237]
**Describe the bug**
When trying to memoize the table row with mode set to MultiSelect, it throws error

**Isolated Example**
```
  const MemoizedRow = React.memo((props) => {
    const { applicant, columnAccessors, index } = props;

    return (
      <TableRow key={`applicantrow_${applicant.sysCandidateId}`} data-candidate-id={applicant.sysCandidateId} ref={index === firstNewRowIndex ? firstNewRowRef : null}>
        {columnAccessors.map((columnAccessor) => (
          <TableCell key={`applicantrow_${applicant.sysCandidateId}_${columnAccessor}`}>{renderTableCell(applicant, columnAccessor)}</TableCell>
        ))}
      </TableRow>
    );
  });
  MemoizedRow.displayName = "MemoizedRow";

          <Table
            data-testid="dataTable"
            onRowClick={onRowClicked}
            onSelectionChange={onRowSelected}
            growing={totalNoOfRows > visibleRows ? TableGrowingMode.Button : TableGrowingMode.None}
            growingButtonText={i18n.getText("COMMON_More")}
            growingButtonSubtext={`[ ${visibleRows} / ${totalNoOfRows} ]`}
            onLoadMore={loadMore}
            mode={TableSelectionMode.MultiSelect}
            columns={cols.map((col) => (
              <TableColumn
                minWidth={DEFAULT_POPIN_COLUMNS.includes(col.accessor) ? 0 : POPIN_WIDTH}
                style={{ width: ACTIONS_COLUMNS.includes(col.accessor) ? "1rem" : "auto" }}
                popinText={col.label}
                key={col.id}
              >
                {col.label}
              </TableColumn>
            ))}
          >
            {data.map((applicant, index) => (
              <MemoizedRow key={`applicantrow_${applicant.sysCandidateId}`} applicant={applicant} index={index} columnAccessors={columnAccessors} />
            ))}
          </Table>
```

Error:
```
Uncaught TypeError: Cannot read properties of undefined (reading 'hasAttribute')
    at TableRow._activeElementHasAttribute (TableRow.js:307:1)
    at TableRow._onrowclick (TableRow.js:291:1)
```

**Expected behavior**
TableRow memoization should work when MultiSelect mode is selected

**Screenshots**

![Screen Shot 2022-07-12 at 1 51 05 PM](https://user-images.githubusercontent.com/65705637/178593091-8d4f6ddf-fad0-41d0-8635-0bd25d4a2104.png)

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: 1.4.0
`@ui5/webcomponents-react` version: 0.25.2

**Comment by gurkirpalgill** [comment]
> 

@Lukas742 I am not able to access sandbox. looks like it's blocked by IT. do you have any other link?

**Comment by Lukas742** [comment]
I cloned the codeSandbox to a GitHub repository you can find [here](https://github.com/Lukas742/memoized-list-example).

If you need to edit the example, please fork this repo, apply the changes in your fork and post the link to it here.
