### ISSUE TITLE
DateRangePicker: Entering a single date manually creates javascript errors and break component

### ISSUE THREAD

**Issue by joe-skrzypczak-fioneer** [SAP/ui5-webcomponents-react#3434]
**Describe the bug**
Entering a single date manually in a date range picker causes the component to break.

**Isolated Example**
Can be reproduced on the current sandbox (https://sap.github.io/ui5-webcomponents-react/?path=/docs/inputs-daterangepicker--default-story)

**To Reproduce**
1. Navigate to https://sap.github.io/ui5-webcomponents-react/?path=/docs/inputs-daterangepicker--default-story
2. Open the browser's debug tools and view console
3. Click on the date range picker component
4. Using the keyboard enter the valid single date JAN 20, 2022 and hit enter
5. You'll see the following stack trace in console: 
8795.fc2c3cff.iframe.bundle.js:2 Uncaught TypeError: Cannot read properties of null (reading 'getTime')
    at DateRangePicker._extractFirstTimestamp (8795.fc2c3cff.iframe.bundle.js:2:5608570)
    at DateRangePicker.normalizeValue (8795.fc2c3cff.iframe.bundle.js:2:5606355)
    at DateRangePicker._updateValueAndFireEvents (8795.fc2c3cff.iframe.bundle.js:2:5599141)
    at DateRangePicker._onInputChange (8795.fc2c3cff.iframe.bundle.js:2:5599833)
    at I.handleEvent (8795.fc2c3cff.iframe.bundle.js:2:9944337)
    at Input._fireEvent (8795.fc2c3cff.iframe.bundle.js:2:1042318)
    at Input.fireEvent (8795.fc2c3cff.iframe.bundle.js:2:1041934)
    at Input._handleChange (8795.fc2c3cff.iframe.bundle.js:2:5703899)
    at I.handleEvent (8795.fc2c3cff.iframe.bundle.js:2:9944337)

**Expected behavior**
Either a validation error is displayed or the entry is considered a valid single day range.

**Screenshots**
![image](https://user-images.githubusercontent.com/95598428/186984608-7cd76f8a-5b17-42d4-b93b-4775e67336dd.png)

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: current version on playground
`@ui5/webcomponents-react` version: latest version on playground
Operating System: Windows
Browser: Chrome

**Additional context**

**Comment by Lukas742** [comment]
Thanks for reporting! I'll forward this issue to our UI5 Web Components Colleagues as the affected component is developed in their repository.
