### ISSUE TITLE
Filterbar + multicombox: error when change value set in filterconfig

### ISSUE THREAD

**Issue by bertdeterd** [SAP/ui5-webcomponents-react#3928]
**Describe the bug**
When you select an item for a multicombobox in the filterconfiguration for the filterbar an error is shown in the  chrome console.

main.8266569b.iframe.bundle.js:2 Uncaught TypeError: Cannot read properties of undefined (reading 'reduce')
    at Table.handleCheckBoxChange (main.8266569b.iframe.bundle.js:2:2822830)
    at ComboBox._fireEvent (2596.1f2f48bf.iframe.bundle.js:2:2016115)
    at ComboBox.fireEvent (2596.1f2f48bf.iframe.bundle.js:2:2015528)
    at ComboBox._selectItem (2596.1f2f48bf.iframe.bundle.js:2:5986070)
    at H.handleEvent (2596.1f2f48bf.iframe.bundle.js:2:9865068)
    at List._fireEvent (2596.1f2f48bf.iframe.bundle.js:2:2015912)
    at List.fireEvent (2596.1f2f48bf.iframe.bundle.js:2:2015528)
    at List.onItemPress (2596.1f2f48bf.iframe.bundle.js:2:6182047)
    at StandardListItem._fireEvent (2596.1f2f48bf.iframe.bundle.js:2:2015912)
    at StandardListItem.fireEvent (2596.1f2f48bf.iframe.bundle.js:2:2015528)

**Isolated Example**
See filterbar in https://sap.github.io/ui5-webcomponents-react/?path=/docs/layouts-floorplans-filterbar--default-story
and go to the filterconfiguration in the example, press show values and select / deselect an item in 'multbox w initial selected'

**To Reproduce**
1. Go to '[example](https://sap.github.io/ui5-webcomponents-react/?path=/docs/layouts-floorplans-filterbar--default-story)'
2. Click on 'Filters'
3. Click on Show Values
4. Scroll down to selection item 'Multbox w/ initail selected'
5. Select / deselect an item
6. See error in chrome console

**Expected behavior**
No errors

**Comment by Lukas742** [comment]
Hi @bertdeterd 

the `selection-change` event of the `MultiComboBox` is bubbling up to the `Table` component. This is happening for all components implementing this event. 
This [PR](https://github.com/SAP/ui5-webcomponents-react/pull/3935) will solve this issue. Until it's released you can invoke `stopPropagation` in the `onSelectionChange` handler of the MultiComboBox.

Since I'm not sure if this is the intended behavior, I'm going to forward this issue to the UI5 Web Components repo, as both components are developed there.

Hi colleagues, 

when components which are implementing the `selection-change` event are used inside the `Table` component, the `selection-change` event is bubbling up, invoking the handler of the respective component and the `Table` as well. 
Could you please check if this is the intended behavior. 

I prepared a codeSandbox that should give more information: https://codesandbox.io/s/ui5-webcomponents-forked-eqbtb6?file=/src/index.js
