### ISSUE TITLE
[Grid]: can't test the component with jest 

### ISSUE THREAD

**Issue by almash929** [SAP/ui5-webcomponents-react#4256]
### Describe the bug

We created a component that is using and returning the Grid component in the jsx
when trying to test our component with jest we face the following error:

`TypeError: Cannot read properties of undefined (reading 'addEventListener')

      at addEventListener (node_modules/@ui5/webcomponents-react-base/dist/Device/Media.js:53:43)
      at initMediaQueries (node_modules/@ui5/webcomponents-react-base/dist/Device/Media.js:72:9)
      at node_modules/@ui5/webcomponents-react-base/dist/hooks/useViewportRange.js:13:27
      at commitHookEffectListMount (node_modules/react-dom/cjs/react-dom.development.js:23150:26)
      at commitPassiveMountOnFiber (node_modules/react-dom/cjs/react-dom.development.js:24931:11)
      at commitPassiveMountEffects_complete (node_modules/react-dom/cjs/react-dom.development.js:24891:9)
      at commitPassiveMountEffects_begin (node_modules/react-dom/cjs/react-dom.development.js:24878:7)
      at commitPassiveMountEffects (node_modules/react-dom/cjs/react-dom.development.js:24866:3)
      at flushPassiveEffectsImpl (node_modules/react-dom/cjs/react-dom.development.js:27039:3)
      at flushPassiveEffects (node_modules/react-dom/cjs/react-dom.development.js:26984:14)
      at node_modules/react-dom/cjs/react-dom.development.js:26769:9
      at flushActQueue (node_modules/react/cjs/react.development.js:2667:24)
      at recursivelyFlushAsyncActWork (node_modules/react/cjs/react.development.js:2633:9)
      at node_modules/react/cjs/react.development.js:2545:15`

seems like the issue is coming from this function:
`function initMediaQueries() {
    if (typeof document !== 'undefined') {
        mediaQueries = {
            S: window.matchMedia(getQuery(...RANGE_DEFINITIONS.S)),
            M: window.matchMedia(getQuery(...RANGE_DEFINITIONS.M)),
            L: window.matchMedia(getQuery(...RANGE_DEFINITIONS.L)),
            XL: window.matchMedia(getQuery(...RANGE_DEFINITIONS.XL))
        };
        for (const mediaQueriesKey in mediaQueries) {
            const handler = (event) => {
                if (event.matches) {
                    const params = resolveRangeInfo(mediaQueriesKey);
                    MediaEventProvider.fireEvent(`media`, params);
                }
            };
            **mediaQueries[mediaQueriesKey].addEventListener('change', handler)**;
        }
    }
}`
if I change the layout to be FlexBox instead of Grid than test is not failing.

### Reproduction steps

1. Create a component that retruns the grid layout
2. Test the component with jest
3. jest is failing with error stated above
...

### Expected Behaviour

test will run successfully

### Screenshots or Videos

<img width="893" alt="Screenshot 2023-03-06 at 12 13 44" src="https://user-images.githubusercontent.com/11338260/223081259-27fbc679-3636-417f-adf7-1c07256712be.png">

### UI5 Web Components for React Version

1.9.2

### UI5 Web Components Version

1.10.5

### Browser

Chrome

### Operating System

mac os ventura

**Comment by Lukas742** [comment]
Hi @almash929 

Jest is unfortunately not supported anymore. You can find out why in this description Marcus has given: 
https://github.com/SAP/ui5-webcomponents-react/issues/3975#issuecomment-1381518567

We're almost done with migrating all Jest tests to Cypress and once we're finished we will update the [Test Setup](https://sap.github.io/ui5-webcomponents-react/?path=/docs/knowledge-base-test-setup--docs) section in our documentation and also offer commands and queries for querying web components, to make it easier working with Cypress.

**Comment by Lukas742** [comment]
Hi @almash929 

our updated documentation about testing can now be found [here](https://sap.github.io/ui5-webcomponents-react/?path=/docs/testing-with-cypress-setup--docs).
