### ISSUE TITLE
[Wizard]: throws console error propertyValidator.attributeToProperty is not a function

### ISSUE THREAD

**Issue by sebastian-kraemer** [SAP/ui5-webcomponents-react#4724]
### Describe the bug

When using the Wizard component, the following error is thrown in the console:

Uncaught TypeError: propertyValidator.attributeToProperty is not a function
    at HTMLElement.attributeChangedCallback (UI5Element.ts:505:42)
    at UI5Element.ts:353:28
    at Array.map (<anonymous>)
    at Dialog._updateSlots (UI5Element.ts:315:43)
    at Dialog._processChildren (UI5Element.ts:288:15)
    at Dialog.connectedCallback (UI5Element.ts:192:15)
    at HTMLHtmlElement.<anonymous> (cypress_runner.js:102681:12)
    at domManip (cypress_runner.js:102519:14)
    at jQuery.fn.init.append (cypress_runner.js:102678:10)
    at AutIframe.restoreDom (index-08193975.js:111324:38)

### Isolated Example

https://codesandbox.io/p/sandbox/silly-fast-4f89c9

### Reproduction steps

1. See console errors

### Expected Behaviour

No console error

### UI5 Web Components for React Version

1.16.1

### UI5 Web Components Version

1.14.0

### Browser

Chrome, Edge

### Operating System

Windows 10

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Lukas742** [comment]
Hi @sebastian-kraemer 

Thanks for reporting! I'll forward this issue to our UI5 Web Components Colleagues as the affected component is developed in their repository.

___

Hi colleagues,

the `Wizard` throws an error when initialized with `content-layout="MultipleSteps"`.
I've created a codeSandbox that shows this behavior using only ui5-webcomponents w/o our wrapper: 
https://codesandbox.io/s/ui5-webcomponents-forked-qcwwjt?file=/index.html

Also, your documentation isn't updated to the latest version, at least there is no mention of the `contentLayout` property in your [playground](https://sap.github.io/ui5-webcomponents/playground/components/Wizard/), only in the["next" playground](https://sap.github.io/ui5-webcomponents/main/playground/components/Wizard/) you can find it.
