### ISSUE TITLE
Select: Error when there is a value state message

### ISSUE THREAD

**Issue by vital487** [SAP/ui5-webcomponents-react#4757]
### Describe the bug

Hi,

For some reason when I have a value state in a select and I click sometimes in it, the following errors appear:

`TypeError: this.popover.showAt is not a function
    at Select2.openValueStatePopover (Select.ts:876:17)`

`Uncaught TypeError: this.popover.close is not a function
    at Select2.closeValueStatePopover (Select.ts:881:32)
    at Select2.toggleValueStatePopover (Select.ts:888:9)
    at Select2.onAfterRendering (Select.ts:371:8)
    at Select2._render (UI5Element.ts:707:8)
    at renderImmediately (Render.ts:44:15)
    at RenderQueue.process (RenderQueue.ts:64:4)
    at Render.ts:67:30`

These errors make the select move from one place to another.

### Reproduction steps

1. Set value state as error
2. Set a value state message
3. Open the select and close it

### Expected Behaviour

Should just close the select instead of returning errors and moving it

### UI5 Web Components for React Version

1.13.0

### UI5 Web Components Version

1.12.2

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Lukas742** [comment]
Hi @vital487 

I wasn't able to reproduce this issue with our latest version. Please create a reproducible example by leveraging this [codeSandbox template](https://codesandbox.io/p/sandbox/ui5-webcomponents-react-vite-j65vvg?file=%2Fsrc%2FApp.tsx%3A1%2C1).

**Comment by vital487** [comment]
@Lukas742, in my code sandbox the error happened.

Please check here: https://codesandbox.io/p/sandbox/heuristic-wozniak-vzyk7v?file=%2Fsrc%2FApp.tsx%3A22%2C2

**Comment by Lukas742** [comment]
Thank you! I'll forward this issue to our UI5 Web Components Colleagues as the affected component is developed in their repository and the error occurs also without our wrapper.

___

Hi colleagues,

[here](https://codesandbox.io/p/sandbox/kind-almeida-l2xlgz?file=%2Fsrc%2FApp.tsx%3A11%2C18) you can find a codeSandbox using ui5-webcomponents in React without our wrapper. I wasn't able to reproduce this using plain js though ([codeSandbox](https://codesandbox.io/p/sandbox/kind-almeida-l2xlgz?file=%2Fsrc%2FApp.tsx%3A11%2C18)).
