### ISSUE TITLE
Unit Test: Failures with syntax errors

### ISSUE THREAD

**Issue by petejohnson84** [SAP/ui5-webcomponents-react#491]
After upgrading from 0.8.6 to 0.9.3, many unit tests fail with the following error.

```Test suite failed to run
node_modules/@ui5/webcomponents-react/node_modules/@babel/runtime/helpers/esm/slicedToArray.js:1
({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import arrayWithHoles from "./arrayWithHoles";

SyntaxError: Cannot use import statement outside a module

at ScriptTransformer._transformAndBuildScript (node_modules/@jest/transform/build/ScriptTransformer.js:537:17)
at ScriptTransformer.transform (node_modules/@jest/transform/build/ScriptTransformer.js:579:25)
at Object.<anonymous> (node_modules/@ui5/webcomponents-react/lib/withWebComponent.js:12:46)
```

**To Reproduce**
1. Use the create-react-app with @ui5/webcomponents-react template.
2. Run `npm test`
3. See failure:
```
/node_modules/@ui5/webcomponents-react-base/node_modules/@babel/runtime/helpers/esm/defineProperty.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){export default function _defineProperty(obj, key, value) {

SyntaxError: Unexpected token 'export'

at ScriptTransformer._transformAndBuildScript (node_modules/@jest/transform/build/ScriptTransformer.js:537:17)
at ScriptTransformer.transform (node_modules/@jest/transform/build/ScriptTransformer.js:579:25)
at Object.<anonymous> (node_modules/@ui5/webcomponents-react-base/lib/CssSizeVariables.js:10:47)
```

**Expected behavior**
Unit tests should pass.

**UI5 Web Components for React Information**
Operating System: macOS Catalina
Node Version: 12.16.3
`@ui5/webcomponents-react` version: 0.9.3
Do you have a dependency to`@ui5/webcomponents` in your package.json? If yes, which version?: 1.0.0-rc.7

**Additional context**
To fix the issue, I changed the jest transformIgnorePattern to
`"node_modules/(?!(@ui5|lit-html|@babel)).*\\.js$"`

This is likely not the ideal solution but does hint that something may need adjusting here.

**Comment by MarcusNotheis** [comment]
Fixed and released with `@ui5/webcomponents-react@0.9.4`
