### ISSUE TITLE
[TextArea]: Form serialization doesn't work the same as for <textarea>

### ISSUE THREAD

**Issue by MetalCar** [SAP/ui5-webcomponents-react#4988]
### Describe the bug

The `<TextArea>` component that is provided by ui5 doesn't work like the html `<textarea>` when getting form data within a JS `FormData` object. On my local dev-environment i got also the problem, that my `<TextArea>` value doesn't has entered `\n`.

Please see my isolated example. You can spot the difference easily.

### Isolated Example

https://codesandbox.io/p/sandbox/festive-bassi-j2fx6y

### Reproduction steps

1. Enter in the example in every TextArea a value like
```
A
B
C
```
2. Click on save
3. Check in the Panels the output of the textareas

### Expected Behaviour

The second panel doesn't show any output. I expected that also the second panel shows my output like the others.

### UI5 Web Components for React Version

1.15.1 (local) - ~1.16.0 (in example)

### UI5 Web Components Version

1.13.3 (local) - ~1.18.0 (in example)

### Browser

Chrome, Edge, Firefox

### Operating System

Win11

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Lukas742** [comment]
Hi @MetalCar 

you didn't import the form support feature (`import '@ui5/webcomponents/dist/features/InputElementsFormSupport.js';`), without it native form support is not enabled. (see e.g. [here](https://sap.github.io/ui5-webcomponents-react/?path=/docs/knowledge-base-form-handling--docs) and [here](https://sap.github.io/ui5-webcomponents-react/?path=/docs/inputs-textarea--docs#properties))

Since the behavior differs even with the import I'm going to forward this issue to our UI5 Web Components colleagues, as the `TextArea` is developed in their repo.

___

Hi colleagues,

The HTMLFormElement property `elements` doesn't return the value with line breaks, this can be reproduced w/o our wrapper:

1. Open [codeSandbox](https://codesandbox.io/s/ui5-webcomponents-forked-m9wdls?file=/src/index.js)
2. Enter text with line breaks in both text areas
3. Open console and submit
4. See that the value of the HTML text area includes line breaks, whereas the ui5-textarea doesn't.

When creating the codeSandbox, I additionally noticed that the `ui5-textarea` is throwing an error when focused-out:
```
Uncaught TypeError: Cannot read properties of null (reading 'querySelector')
    at TextArea._onfocusout (TextArea.js:132:66)
    at EventPart.handleEvent (lit-html.js:790:29)
_onfocusout @ TextArea.js:132
handleEvent @ lit-html.js:790
```

https://github.com/SAP/ui5-webcomponents-react/assets/9749730/fd0b3383-2767-488f-b0c4-5691ba37114c
