### ISSUE TITLE
[Shellbar]: Search input is not working with suggestions enabled

### ISSUE THREAD

**Issue by skowrons** [SAP/ui5-webcomponents-react#5153]
### Describe the bug

When the `Input` component has `showSuggestions` set it will not be clickable in the `Shellbar`.

### Isolated Example

https://codesandbox.io/p/sandbox/hungry-mountain-s3vsyz?file=%2Fsrc%2FApp.tsx%3A1%2C1

### Reproduction steps

1. Create a shellbar component
2. Show the search input
3. Add input with `showSuggestions`
4. Cannot input anything

### Expected Behaviour

It should not matter whether we use `SuggestionItem` or not.

### UI5 Web Components for React Version

1.21.1

### UI5 Web Components Version

1.12.2

### Browser

Chrome

### Additional Context

Did not test other browsers.

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by skowrons** [comment]
Here the error log:

```
Uncaught (in promise) Error: You have to import "@ui5/webcomponents/dist/features/InputSuggestions.js" module to use ui5-input suggestions
    at Input2.enableSuggestions (Input.ts:1274:10)
    at Input2.onBeforeRendering (Input.ts:704:9)
    at Input2._render (UI5Element.ts:673:8)
    at renderImmediately (Render.ts:44:15)
    at Input2.connectedCallback (UI5Element.ts:196:3)
```

Just needed to import the described package.
