### ISSUE TITLE
Input: Autocompletion from browser does not change value of onInput or onChange

### ISSUE THREAD

**Issue by jakub-tkacz-emundo** [SAP/ui5-webcomponents-react#5812]
### Describe the bug

When the value is selected from browser suggestions/autocompletion then the `e.target.value` in the `onInput` or `onChange` is empty and error is visible in console.

### Isolated Example

https://stackblitz.com/edit/github-kx12cr?file=src%2FApp.tsx

### Reproduction steps

1. Click on Input
2. Select value from browser's suggestion/autocomplete popover

### Expected Behaviour

When the suggestion is clicked, then both `onInput` and `onChange` should be fired with the selected value

### Screenshots or Videos

<img width="441" alt="Screenshot 2024-05-16 at 15 14 06" src="https://github.com/SAP/ui5-webcomponents-react/assets/158556940/6420768a-9cc2-4067-80be-fedb2550758a">
<img width="412" alt="Screenshot 2024-05-16 at 15 14 12" src="https://github.com/SAP/ui5-webcomponents-react/assets/158556940/298b63f7-413f-4e7d-bde8-ef2c318f85b9">
<img width="529" alt="Screenshot 2024-05-16 at 15 14 22" src="https://github.com/SAP/ui5-webcomponents-react/assets/158556940/c1c84f3b-588a-469f-a272-a31820bdc352">

### UI5 Web Components for React Version

1.28.1

### UI5 Web Components Version

1.24.3

### Browser

Chrome

### Operating System

Mac

### Relevant log output

```shell
Uncaught TypeError: Cannot read properties of undefined (reading 'inputType')
    at Input2._handleInput (@ui5_webcomponents-react.js?v=4ac18bb1:46013:47)
    at EventPart.handleEvent (@ui5_webcomponents-react.js?v=4ac18bb1:24721:29)



Input.ts:1023 Uncaught TypeError: Cannot read properties of undefined (reading 'inputType')
    at Input2._handleInput (Input.ts:1023:38)
    at EventPart.handleEvent (lit-html.ts:2018:29)
```

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Lukas742** [comment]
Hi @jakub-tkacz-emundo 

I will close this issue as there is already [another one](https://github.com/SAP/ui5-webcomponents/issues/8706) covering this topic. If you have any questions or more information, please address them in the original issue.

Duplicate of https://github.com/SAP/ui5-webcomponents/issues/8706
